Console.WriteLine("Holamundodesdegit");
Console.WriteLine("Texto escrito desde visual studio1");
Console.WriteLine("second snapshot");
Console.WriteLine("Holamundodesdegit");
Console.WriteLine("Texto escrito desde visual studio1");
Console.WriteLine("second snapshot");
Console.WriteLine("Holamundodesdegit");
Console.WriteLine("Texto escrito desde visual studio1");
Console.WriteLine("second snapshot");
Console.WriteLine("Holamundodesdegit");
Console.WriteLine("Texto escrito desde visual studio1");
Console.WriteLine("second snapshot");
